### ISSUE TITLE
Unable to get the sample working

### ISSUE THREAD

**Issue by markewallace** [muenzpraeger/salesforce-ibm-verse#1]
Tried using the already deployed application i.e. https://salesforce-ibm-verse.herokuapp.com/verse and I get this message 'You are currently not logged in into Salesforce. Please click the button below.'. If I then login to Salesforce and Grant Access I get stuck redirected to the login page.

I also tried following the 'Run-On-Your-Own' instructions, can you provide more details on how the Connected App needs to be configured?

**Comment by muenzpraeger** [comment]
Hi Mark,

The deployed application connects to one of my Salesforce orgs, so you won't have access to the Lightning Components.

- Install the app on Heroku.
- You'll find instructions for how to setup a Connected App with OAuth API access [here](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_defining_remote_access_applications.htm). The callback needs to point to your https://yourapp.herokuapp.com/oauthcallback.
- Apply the created Consumer Key and Consumer Secret in the config settings for your Heroku app.
- Also define the URL of the source Connections Cloud Mail url in the Heroku settings for the CORS check.
- Install the unmanaged package into your Developer Edition Org (link [here](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t0Y000000IswW)). That'll add the Lightning Components and Apex classes to your DE org.

Cheers,
René

**Comment by markewallace** [comment]
The install unmanaged package step didn't work for me, I get this error:
```
Your request to install package "IBM Verse Initial Version" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: IBM (00D0Y000000sIL6)
User: Mark Wallace (0050Y000000K0HV)
Package: IBM Verse (04t0Y000000IswW)

Problem:

1.  Duplicate Name
The name "https_salesforce_ibm_verse_herokuapp_com" is already used on component type: CORS Whitelist Origin. Please rename existing component.
```

**Comment by muenzpraeger** [comment]
The error message says that you've already set up a CORS definition - and as stated you've to remove that.

**Comment by markewallace** [comment]
My application is deployed here: `https://ibm-verse-salesforce.herokuapp.com/verse`
In my CORS config I have this: `https://ibm-verse-salesforce.herokuapp.com`

When I run the integration I get to the 'Login to Salesforce' screen. When I click a window flashes open then closes and I'm still at the login screen.

**Comment by markewallace** [comment]
OK removed CORS and now I get this error:
```
This app can't be installed.
There are problems that prevent this package from being installed.
Missing Organization Feature: Email2Case
```

**Comment by muenzpraeger** [comment]
Seems you haven't enabled that functionality. To resolve this navigate to Setup > Customize > Cases > Email-to-Case. Only the first checkbox labeled "Enable Email-to-Case" needs to be checked. It is not necessary to make any other configuration changes there.

**Comment by markewallace** [comment]
Great, the installation completed this time. I'm still stuck in the login loop. Am I able to create a user account for you in my Salesforce org so you can see what I'm seeing?

**Comment by muenzpraeger** [comment]
I would check first the JavaScript console when logging in. If that doesn't work => send me the login details via Twitter DM (my user is @muenzpraeger).

**Comment by markewallace** [comment]
I have checked the JS console and it's empty. Will DM you the credentials.
